<a href="https://colab.research.google.com/github/ryanglenc/MAT_442/blob/main/MAT_442_HW_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



This notebook demonstrates the key concepts from Section 1.2 using small worked examples in Python (NumPy).

In [6]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

## 1.2.1 Linear Spaces

A set of vectors is **linearly independent** if no vector in the set can be written as a combination of the others.
We can check this using the **rank** of the matrix formed by the vectors: if the rank equals the number of vectors, they are independent and form a **basis** for their span.

In [7]:
# Three vectors in R^3
v1 = np.array([1, 5, 7])
v2 = np.array([2, 1, 0])
v3 = np.array([0, 11, 101])   # note: v3 = 2*v2 - v1... let's check dependency

M = np.array([v1, v2, v3])
rank = np.linalg.matrix_rank(M)

print("Matrix of vectors:\n", M)
print("Rank:", rank)

if rank == M.shape[0]:
    print("The vectors are linearly independent and form a basis for their span.")
else:
    print("The vectors are linearly dependent — they do not form a basis.")

Matrix of vectors:
 [[  1   5   7]
 [  2   1   0]
 [  0  11 101]]
Rank: 3
The vectors are linearly independent and form a basis for their span.


## 1.2.2 Orthogonality

Two vectors **u** and **v** are orthogonal if their dot product is zero: u · v = 0.
The **projection** of a vector **b** onto a vector **a** is given by:

proj_a(b) = ( (a · b) / (a · a) ) * a

We'll check orthogonality between two vectors, then compute a projection.

In [8]:
a = np.array([3, 0, -1])
b = np.array([1, 1, 1])

dot_ab = np.dot(a, b)
print(f"a · b = {dot_ab}")
print("Orthogonal!" if dot_ab == 0 else "Not orthogonal.")

# Projection of a new vector c onto a
c = np.array([2, 3, 1])
proj_c_on_a = (np.dot(a, c) / np.dot(a, a)) * a
print("\nProjection of c onto a:", proj_c_on_a)

# Verify: (c - proj) should be orthogonal to a
residual = c - proj_c_on_a
print("Residual · a =", np.dot(residual, a), "(should be ~0)")

a · b = 2
Not orthogonal.

Projection of c onto a: [ 1.5  0.  -0.5]
Residual · a = 0.0 (should be ~0)


## 1.2.3 Gram–Schmidt Process

Gram–Schmidt converts a set of linearly independent vectors into an **orthonormal** set (mutually orthogonal, unit length), by subtracting off projections onto previous vectors, then normalizing.

We implement it manually here, then verify orthonormality, and cross-check with NumPy's QR decomposition.

In [9]:
def gram_schmidt(vectors):
    basis = []
    for v in vectors:
        w = v.astype(float).copy()
        for u in basis:
            w -= (np.dot(v, u) / np.dot(u, u)) * u
        u_normalized = w / np.linalg.norm(w)
        basis.append(u_normalized)
    return np.array(basis)

vectors = [np.array([1, 1, 0]), np.array([1, 0, 1]), np.array([0, 1, 1])]
ortho_basis = gram_schmidt(vectors)

print("Orthonormal basis:\n", ortho_basis)

# Verify orthogonality (dot products between different vectors ~0)
print("\nDot products (should be ~0 off-diagonal, ~1 on diagonal):")
print(ortho_basis @ ortho_basis.T)

# Cross-check with numpy's QR decomposition
Q, R = np.linalg.qr(np.array(vectors).T.astype(float))
print("\nNumPy QR orthonormal columns (Q):\n", Q.T)

Orthonormal basis:
 [[ 0.7071  0.7071  0.    ]
 [ 0.4082 -0.4082  0.8165]
 [-0.5774  0.5774  0.5774]]

Dot products (should be ~0 off-diagonal, ~1 on diagonal):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

NumPy QR orthonormal columns (Q):
 [[-0.7071 -0.7071 -0.    ]
 [ 0.4082 -0.4082  0.8165]
 [-0.5774  0.5774  0.5774]]


## 1.2.4 Eigenvalues and Eigenvectors

For a square matrix A, an eigenvector **v** and eigenvalue λ satisfy:

A v = λ v

We compute both using NumPy, then verify the equation directly.

In [10]:
A = np.array([[4, 1],
              [2, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors (columns):\n", eigenvectors)

# Verify A v = lambda v for the first eigenpair
v = eigenvectors[:, 0]
lam = eigenvalues[0]

Av = A @ v
lambda_v = lam * v

print("\nA @ v      =", Av)
print("lambda * v =", lambda_v)
print("Match:", np.allclose(Av, lambda_v))

Eigenvalues: [5. 2.]
Eigenvectors (columns):
 [[ 0.7071 -0.4472]
 [ 0.7071  0.8944]]

A @ v      = [3.5355 3.5355]
lambda * v = [3.5355 3.5355]
Match: True


## Summary

- **1.2.1**: Verified linear independence via matrix rank.
- **1.2.2**: Checked orthogonality via dot product and computed a vector projection.
- **1.2.3**: Implemented Gram–Schmidt manually and verified orthonormality against NumPy's QR decomposition.
- **1.2.4**: Computed eigenvalues/eigenvectors and verified Av = λv directly.